# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: README.md
    - id: check-yaml
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-executables-have-shebangs
